runtime: nodejs14 # or another supported version
includes:
  - env_variables.yaml
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto